package com.chronus.ai.service;

import com.chronus.ai.model.AiSuggestion;
import com.chronus.ai.model.ChatResponse;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Service
public class AiService {

    @Value("${ai.api.key}")
    private String apiKey;

    @Value("${ai.api.url}")
    private String apiUrl; // e.g., https://api.openai.com/v1/chat/completions

    private final RestTemplate restTemplate = new RestTemplate();
    private final ObjectMapper objectMapper = new ObjectMapper();

    public ChatResponse chat(String message, String mode) {
        try {
            // Prepare headers
            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);
            headers.setBearerAuth(apiKey);

            // Prepare body
            Map<String, Object> body = new HashMap<>();
            body.put("model", "gpt-3.5-turbo"); // Or gpt-4
            
            String systemPrompt = """
                You are a planning assistant Chronus. 
                Analyze the user's request and current mode ("%s").
                Return a JSON object with:
                1. "reply": A friendly response.
                2. "suggestions": An array of tasks derived from the request.
                   Each task has: "name", "duration" (minutes), "mode" (todo/study/final), "priority" (high/medium/low), "reason".
                
                Example JSON:
                {
                  "reply": "I've added a study session for you.",
                  "suggestions": [
                    { "name": "Read Chapter 1", "duration": 45, "mode": "study", "priority": "high", "reason": "Core material" }
                  ]
                }
                IMPORTANT: Output ONLY valid JSON. No markdown blocks.
                """.formatted(mode);

            List<Map<String, String>> messages = new ArrayList<>();
            messages.add(Map.of("role", "system", "content", systemPrompt));
            messages.add(Map.of("role", "user", "content", message));

            body.put("messages", messages);
            body.put("temperature", 0.7);

            HttpEntity<Map<String, Object>> request = new HttpEntity<>(body, headers);

            // Call API
            // Note: If apiUrl is not set or invalid, this will throw.
            // For hackathon/demo, we assume valid config or handle error.
            if (apiUrl == null || apiUrl.isEmpty() || apiKey == null || apiKey.equals("FAKE_KEY")) {
                return mockResponse(message, mode);
            }

            ResponseEntity<Map> response = restTemplate.postForEntity(apiUrl, request, Map.class);
            
            if (response.getBody() != null) {
                List<Map> choices = (List<Map>) response.getBody().get("choices");
                if (choices != null && !choices.isEmpty()) {
                    Map messageObj = (Map) choices.get(0).get("message");
                    String content = (String) messageObj.get("content");
                    return objectMapper.readValue(content, ChatResponse.class);
                }
            }
            
            return mockResponse(message, mode); // Fallback

        } catch (Exception e) {
            e.printStackTrace();
            return mockResponse(message, mode); // Fallback on error
        }
    }

    // Fallback Mock for Demo stability
    private ChatResponse mockResponse(String message, String mode) {
        ChatResponse response = new ChatResponse();
        response.setReply("I'm simulating a response because the AI API is not configured or reachable. (Mode: " + mode + ")");
        
        List<AiSuggestion> suggestions = new ArrayList<>();
        AiSuggestion task = new AiSuggestion();
        task.setName("Sample Task from " + message);
        task.setDuration(30);
        task.setMode(mode);
        task.setPriority("medium");
        task.setReason("Generated by fallback logic");
        suggestions.add(task);
        
        response.setSuggestions(suggestions);
        return response;
    }
}
